//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contactz.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addressbook
    {
        public int ID { get; set; }
        public Nullable<int> ContactID { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
