//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contactz.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public byte[] Photo { get; set; }
        public string Category { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> MobileInt { get; set; }
    
        public virtual Addressbook Addressbook { get; set; }
    }
}
